spor/blog/urls.py
from django.urls import path

from . import views
import search.views

urlpatterns = [
    path('', views.index),
    path('post/<slug>/', views.blog_post, name='post-detail'),
    path('posts/<year>/', views.year_archive, name='posts-year-archive'),
    path('posts/<year>/<month>/', views.month_archive, name='posts-month-archive'),
    path('posts/<year>/<month>/<day>/', views.day_archive, name='posts-day-archive'),
    path('category/<category>/', views.post_category, name="post-category"),
    path('tag/<tag>/', views.post_tag, name="post-tag"),
    path('search/', search.views.search),
    path('search/<slug>/', search.views.search_blog, name="search-blog"),
]

spor/spor/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
import home.views

urlpatterns = [
    path('about/', home.views.about),
    path('help/', home.views.help_page),
    path('events/', include('events.urls')),
    path('investigations/', include('investigations.urls')),
    path('research/', include('research.urls')),
    path('blog/', include('blog.urls')),
    path('services/', home.views.services),
    path('contact/', home.views.contact_page),
    path('area51/', include('area51.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('', home.views.index),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spor/home/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
import uuid


class BaseModel(models.Model):
    """
    """
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    class Meta(object):
        abstract = True


class UserProfile(BaseModel):
    """
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __unicode__(self):
        return "{fname} {lname}".format(
            fname=self.user.first_name,
            lname=self.user.last_name
        )

    def full_name(self):
        return "{fname} {lname}".format(
            fname=self.user.first_name,
            lname=self.user.last_name
        )


class FAQ(BaseModel):
    """
    """
    question = models.CharField(max_length=255, help_text="Plain text or HTML input is accepted.")
    answer = models.TextField(help_text="Plain text or HTML input is accepted.")
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.question

    class Meta(object):
        verbose_name = "FAQ"


class BugCategory(BaseModel):
    """
    """
    name = models.CharField(max_length=25)
    value = models.CharField(max_length=50)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta(object):
        verbose_name_plural = "Bug Categories"


class BugReport(BaseModel):
    """
    """
    # Make these integer based
    BUG_SEVERITY = (
        ("none", "Non-Issue"),
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("critical", "Critical"),
    )

    BUG_STATUS = (
        ("review", "Review"),
        ("scheduled_fix", "Scheduled Fix"),
        ("in_progress", "In Progress"),
        ("fixed", "Fixed"),
        ("closed", "Closed"),
        ("blocked", "Blocked"),
    )

    category = models.ForeignKey(BugCategory, on_delete=models.PROTECT)
    description = models.TextField()
    severity = models.CharField(max_length=25, choices=BUG_SEVERITY, default="low")
    assignee = models.ForeignKey(User, null=True, blank=True, on_delete=models.PROTECT)
    notes = models.TextField(blank=True)
    status = models.CharField(max_length=25, choices=BUG_STATUS, default="review")
    date_submitted = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "{name} - {date}".format(
            name=self.category.name,
            date=self.date_submitted
        )

    class Meta(object):
        verbose_name = "Bug Report"


class KnownIssue(BaseModel):
    """
    """
    tagline = models.CharField(max_length=255, help_text="Plain text or HTML input is accepted.")
    reference_bug = models.ForeignKey(BugReport, blank=True, null=True, on_delete=models.PROTECT)
    description = models.TextField(help_text="Plain text or HTML input is accepted.")
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.tagline

    class Meta(object):
        verbose_name = "Known Issue"


class TeamMember(BaseModel):
    """
    """
    first_name = models.CharField(max_length=50, verbose_name="First Name")
    last_name = models.CharField(max_length=100, verbose_name="Last Name")
    title = models.CharField(max_length=50, default="Member")
    thumbnail = models.ImageField(upload_to="images/team", help_text="750x450 works the best")
    description = models.TextField()
    date_joined = models.DateField(blank=True)
    facebook = models.BooleanField(default=False)
    facebook_url = models.URLField(blank=True)
    twitter = models.BooleanField(default=False)
    twitter_url = models.URLField(blank=True)
    linkedin = models.BooleanField(default=False)
    linkedin_url = models.URLField(blank=True)

    def __unicode__(self):
        return "{fname} {lname}".format(fname=self.first_name, lname=self.last_name)

    class Meta(object):
        verbose_name = "Team Member"


class Partner(BaseModel):
    """
    """
    name = models.CharField(max_length=50)
    thumbnail = models.ImageField(upload_to="images/customers", help_text="500x300 works the best")
    url = models.URLField(blank=True)

    def __unicode__(self):
        return self.name


class Contact(BaseModel):
    """
    """
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=20)
    phone = models.CharField(max_length=25)
    email = models.EmailField()
    hours = models.CharField(max_length=255)
    google_map_url = models.CharField(max_length=255, blank=True, null=True, help_text="You can override the provided value, or set it blank to regenerate it")
    facebook = models.BooleanField(default=False)
    facebook_url = models.URLField(blank=True)
    twitter = models.BooleanField(default=False)
    twitter_url = models.URLField(blank=True)
    linkedin = models.BooleanField(default=False)
    linkedin_url = models.URLField(blank=True)
    gplus = models.BooleanField(default=False)
    gplus_url = models.URLField(blank=True)
    primary_contact = models.BooleanField(default=False, help_text="Primary contacts will show up on our contact page")

    def __unicode__(self):
        return "{address} {city}, {state} {zipcode}".format(
            address=self.address,
            city=self.city,
            state=self.state,
            zipcode=self.zipcode
        )

    def save(self, *args, **kw):
        if not self.google_map_url:
            from django.conf import settings
            uri = "{address},{city}+{state}".format(address=self.address.replace(" ", "+"), city=self.city, state=self.state)
            self.google_map_url = "https://www.google.com/maps/embed/v1/place?key={key}&q={uri}".format(key=settings.GOOGLE_MAPS_EMBED_API_KEY, uri=uri)
        super(Contact, self).save(*args, **kw)


class Banner(BaseModel):
    """
    """
    image = models.ImageField(upload_to="images/banners")
    caption = models.CharField(max_length=25)

    def __unicode__(self):
        return self.caption


class Alert(BaseModel):
    """
    """
    SEVERITY = (
        ("info", "Info"),
        ("warning", "Warning"),
        ("success", "Good"),
        ("danger", "Bad")
    )

    severity = models.CharField(max_length=10, choices=SEVERITY, default="info")
    header = models.CharField(max_length=25, help_text="Plain text or HTML input is accepted.")
    body = models.TextField(help_text="Plain text or HTML input is accepted.")
    dismissable = models.BooleanField(default=False)
    enabled = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.header


class Modal(BaseModel):
    """
    """
    SEVERITY = (
        ("default", "Default"),
        ("info", "Info"),
        ("warning", "Warning"),
        ("success", "Good"),
        ("danger", "Bad")
    )

    severity = models.CharField(max_length=10, choices=SEVERITY, default="default")
    header = models.CharField(max_length=25)
    body = models.TextField(help_text="Plain text or HTML input is accepted.")
    popup = models.BooleanField(default=False)
    enabled = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.header

spor/services/models.py
from __future__ import unicode_literals

# from django.db import models

# Create your models here.

spor/home/forms.py
from django import forms
from .models import BugCategory, BugReport

class BugReportForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=BugCategory.objects.order_by('name'))
    category.widget.attrs.update({'class': 'form-control'})
    description = forms.CharField(widget=forms.Textarea, required=True)
    description.widget.attrs.update({
        'class': 'form-control',
        'placeholder': 'Description',
        'rows': 3
    })

    class Meta(object):
        model = BugReport
        fields = ['category', 'description',]

spor/home/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import FAQ, KnownIssue, TeamMember, Partner, Contact
from .forms import BugReportForm


def index(request):
    return render(request, 'home/index.html')


def about(request):
    team_members = TeamMember.objects.all()
    partners = Partner.objects.all()
    return render(request, 'home/about.html', {'team_members': team_members, 'partners': partners})


def services(request):
    return render(request, 'home/services.html')

def help_page(request):
    """
    """
    faqs = FAQ.objects.all()
    issues = KnownIssue.objects.exclude(reference_bug__status__in=["Fixed", "Closed"])

    if request.method == 'POST':
        form = BugReportForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, """
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <i class="fa fa-check-circle" aria-hidden="true"></i> <strong>Bug Rreport submitted!</strong> Thank you for your feedback!
                </div>
            """)
            return HttpResponseRedirect('/help/')
    else:
        form = BugReportForm()

    return render(request, 'home/help.html', {'faqs': faqs, 'issues': issues, 'form': form})


def contact_page(request):
    contact = Contact.objects.get(primary_contact=True)
    return render(request, 'home/contact.html', {'contact': contact})

spor/services/views.py
# from django.shortcuts import render

# Create your views here.

spor/home/templates/home/about.html
{% extends 'home/wrapper.html' %}

{% block content %}
<!-- Page Heading/Breadcrumbs -->
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">About
			<small>Subheading</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="/">Home</a>
			</li>
			<li class="active">About</li>
		</ol>
	</div>
</div>
<!-- /.row -->

<!-- Intro Content -->
<div class="row">
	<div class="col-md-6">
		<img class="img-responsive img-rounded" src="http://placehold.it/750x450" alt="">
	</div>
	<div class="col-md-6">
		<h2>About <abbr title="Society of Paranormal and Occult Research">SPOR</abbr></h2>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed voluptate nihil eum consectetur similique? Consectetur, quod, incidunt, harum nisi dolores delectus reprehenderit voluptatem perferendis dicta dolorem non blanditiis ex fugiat.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, magni, aperiam vitae illum voluptatum aut sequi impedit non velit ab ea pariatur sint quidem corporis eveniet. Odit, temporibus reprehenderit dolorum!</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, consequuntur, modi mollitia corporis ipsa voluptate corrupti eum ratione ex ea praesentium quibusdam? Aut, in eum facere corrupti necessitatibus perspiciatis quis?</p>
	</div>
</div><!-- /.row -->

<!-- Team Members -->
<div class="row">
	<div class="col-lg-12">
		<h2 class="page-header">Our Team</h2>
	</div>
	{% for i in team_members %}
	<div class="col-md-4 text-center">
		<div class="thumbnail">
			<img class="img-responsive img-rounded" src="{{ MEDIA_URL }}{{ i.thumbnail.url }}" alt="{{ i.fname }} {{ i.lname }}">
			<div class="caption">
				<h3>{{ i.first_name }} {{ i.last_name }}<br>
					<small>{{ i.title }}</small>
				</h3>
				<p>{{ i.description }}</p>
				<ul class="list-inline">
					{% if i.facebook %}<li><a target="_blank" href="{{ i.facebook_url }}"><i class="fa fa-2x fa-facebook-square"></i></a></li>{% endif %}
					{% if i.linkedin %}<li><a target="_blank" href="{{ i.linkedin_url }}"><i class="fa fa-2x fa-linkedin-square"></i></a></li>{% endif %}
					{% if i.twitter %}<li><a target="_blank" href="{{ i.twitter_url }}"><i class="fa fa-2x fa-twitter-square"></i></a></li>{% endif %}
				</ul>
			</div>
		</div>
	</div>
	{% empty %}
	<div class="col-md-12">
		<p>We currently don't have any team members. This is most likely in error!</p>
	</div>
	{% endfor %}
</div><!-- /.row -->

<!-- Call to Action Section -->
<div class="well">
  <div class="row">
    <div class="col-md-8">
    	<h4>Interested in joining our team?</h4>
      <p>If you think you have the experience and drive to join our team, please feel free to submit an application.</p>
    </div>
    <div class="col-md-4">
      <button class="btn btn-lg btn-default btn-block" type="button" data-toggle="modal" data-target="#recruitModal">Apply Now</button>
    </div>
  </div>
</div>

<!-- Our Customers -->
<div class="row">
	<div class="col-lg-12">
		<h2 class="page-header">Our Partners</h2>
	</div>
	{% for j in partners %}
	<div class="col-md-2 col-sm-4 col-xs-6">
		<img class="img-responsive img-rounded customer-img" src="{{ j.thumbnail.url }}" alt="{{ j.name }}">
	</div>
	{% empty %}
	<div class="col-md-12 col-sm-12 col-xs-12">
		<p>None Yet! Maybe you will be our first one?</p>
	</div>
	{% endfor %}
</div><!-- /.row -->

<!-- Modal -->
<div class="modal fade" id="recruitModal" tabindex="-1" role="dialog" aria-labelledby="recruitmentForm">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="RecruitmentForm">Apply to Join</h4>
      </div>
      <div class="modal-body">
      	<iframe src="https://docs.google.com/forms/d/1f8EkYXjThragmtJxBEWXQFB8qIUuMgn-m70Zn--aoUQ/viewform?embedded=true" width="100%" height="600" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Submit</button> -->
      </div>
    </div>
  </div>
</div>
{% endblock %}

spor/home/templates/home/contact.html
{% extends 'home/wrapper.html' %}

{% block content %}

<!-- Page Heading/Breadcrumbs -->
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Contact
			<small>Subheading</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="/">Home</a></li>
			<li class="active">Contact</li>
		</ol>
	</div>
</div><!-- /.row -->

<!-- Content Row -->
<div class="row">
	{% if contact %}
	<!-- Map Column -->
	<div class="col-md-8">
		<iframe src="{{ contact.google_map_url }}" width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" allowfullscreen></iframe>
	</div>
	<!-- Contact Details Column -->
	<div class="col-md-4">
		<h3>Contact Details</h3>
		<p>{{ contact.address }}<br>{{ contact.city }}, {{ contact.state }} {{ contact.zipcode }}<br></p>
		<p><i class="fa fa-phone fa-fw"></i> <abbr title="Phone">P</abbr>: {{ contact.phone }}</p>
		<p><i class="fa fa-envelope-o fa-fw"></i> <abbr title="Email">E</abbr>: <a href="mailto:{{ contact.email }}">{{ contact.email }}</a></p>
		<p><i class="fa fa-clock-o fa-fw"></i> <abbr title="Hours">H</abbr>: {{ contact.hours }}</p>
		<ul class="list-unstyled list-inline list-social-icons">
			{% if contact.facebook %}<li><a href="{{ contact.facebook_url }}"><i class="fa fa-facebook-square fa-2x"></i></a></li>{% endif %}
			{% if contact.linkedin %}<li><a href="{{ contact.linkedin_url }}"><i class="fa fa-linkedin-square fa-2x"></i></a></li>{% endif %}
			{% if contact.twitter %}<li><a href="{{ contact.twitter_url }}"><i class="fa fa-twitter-square fa-2x"></i></a></li>{% endif %}
			{% if contact.gplus %}<li><a href="{{ contact.gplus_url }}"><i class="fa fa-google-plus-square fa-2x"></i></a></li>{% endif %}
		</ul>
	</div>
	{% else %}
		<div class="col-md-12">
			<p>No contact information is currently available.</p>
		</div>
	{% endif %}
</div><!-- /.row -->

<!-- Contact Form -->
<!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
<div class="row">
	<div class="col-md-8">
		<h3>Send us a Message</h3>
		<form name="sentMessage" id="contactForm" novalidate>
			<div class="control-group form-group">
				<div class="controls">
					<label for="name" class="sr-only">Full Name:</label>
					<input type="text" class="form-control" id="name" placeholder="Full Name" required data-validation-required-message="Please enter your name.">
					<p class="help-block"></p>
				</div>
			</div>
			<div class="control-group form-group">
				<div class="controls">
					<label for="phone" class="sr-only">Phone Number:</label>
					<input type="tel" class="form-control" id="phone" placeholder="Phone Number" required data-validation-required-message="Please enter your phone number.">
				</div>
			</div>
			<div class="control-group form-group">
				<div class="controls">
					<label for="email" class="sr-only">Email Address:</label>
					<input type="email" class="form-control" id="email" placeholder="Email Address" required data-validation-required-message="Please enter your email address.">
				</div>
			</div>
			<div class="control-group form-group">
				<div class="controls">
					<label for="message" class="sr-only">Message:</label>
					<textarea rows="10" cols="100" class="form-control" id="message" placeholder="Message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
				</div>
			</div>
			<div id="success"></div>
			<!-- For success/fail messages -->
			<button type="submit" class="btn btn-primary">Send Message</button>
		</form>
	</div>
</div><!-- /.row -->

{% endblock %}

spor/home/templates/home/help.html
{% extends 'home/wrapper.html' %}

{% block content %}

<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Help
      <small>Subheading</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">Help</li>
    </ol>
  </div>
</div>
<!-- /.row -->

<!-- Content Row -->
<div class="row">
  <div class="col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-question-circle fa-fw" aria-hidden="true"></i> Frequently Asked Questions</h3>
      </div>
      <div class="panel-body">
        <div class="panel-group" id="accordion">
          {% for i in faqs %}
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_{{ forloop.counter }}">{{ i.question|safe }}</a>
              </h4>
            </div>
            <div id="collapse_{{ forloop.counter }}" class="panel-collapse collapse {% if forloop.first %}in{% endif %}">
              <div class="panel-body">{{ i.answer|safe }}</div>
            </div>
          </div><!-- /.panel -->
          {% empty %}
          <div class="panel panel-default">
            <div class="panel-body">
              <span class="text-warning"><i class="fa fa-exclamation-circle" aria-hidden="true"></i> There are currently no frequently asked questions, this is most likely in error!</span>
            </div>
          </div>
          {% endfor %}
        </div><!-- /.panel-group -->
      </div><!-- /.panel-body -->
    </div><!-- /.panel -->
  </div><!-- /.col-lg-6 -->
  <div class="col-lg-6">
    <form method="POST">
      {% csrf_token %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title"><i class="fa fa-bug fa-fw" aria-hidden="true"></i> Bug Report</h4>
        </div><!-- /.panel-heading -->
        <div class="panel-body">
          <p>Before submitting a bug report, please take a look at our known issues. If your issue is not represented there, please submit a bug report with as much information as possible.</p>
          <ul class="list-group">
            {% for j in issues %}
            <li class="list-group-item">
              <p><strong>{{ j.tagline|safe }}</strong></p>
              <p><small>{{ j.description|safe }}</small></p>
              {% if j.reference_bug %}
              <p>
                <small><i class="fa fa-fire fa-fw" aria-hidden="true"></i> Severity: {{ j.reference_bug.get_severity_display }}</small>,
                <small><i class="fa fa-heartbeat fa-fw" aria-hidden="true"></i> Status: {{ j.reference_bug.get_status_display }}</small>
              </p>
              {% endif %}
            </li>
            {% empty %}
            <li class="list-group-item list-group-item-success"><i class="fa fa-check-circle" aria-hidden="true"></i> There are currently no known issues. Yay!</li>
            {% endfor %}
          </ul>
          {{ form.non_field_errors }}
          <div class="form-group {% if form.category.errors %}has-error{% endif %}">
            {{ form.category }}
            {% if form.category.errors %}
            <p><small class="text-danger">{{ form.description.errors }}</small></p>
            {% endif %}
          </div>
          <div class="form-group {% if form.description.errors %}has-error{% endif %}">
            {{ form.description }}
            {% if form.description.errors %}
            <p><small class="text-danger">{{ form.description.errors }}</small></p>
            {% endif %}
          </div>
          {% if messages %}
            {% for message in messages %}
            {{ message|safe }}
            {% endfor %}
          {% endif %}
        </div><!-- /.panel-body -->
        <div class="panel-footer text-right">
          <button type="submit" class="btn btn-default"><i class="fa fa-paper-plane fa-fw" aria-hidden="true"></i> Submit</button>
        </div><!-- /.panel-footer -->
      </div><!-- /.panel -->
    </form>
  </div><!-- /.col-lg-6 -->
</div><!-- /.row -->

{% endblock %}

spor/home/templates/home/wrapper.html
{% extends 'home/base.html' %}

{% block properties %}{% endblock %}

{% block inlinecss %}{% endblock %}

{% block alerts %}
{% for alert in site_alerts %}
{% if alert.enabled %}
<div class="container-fluid" {% if forloop.first %}style="margin-top: 20px;"{% endif %}>
  <div class="alert alert-block alert-{{ alert.severity }} {% if alert.dismissable %}alert-dismissible{% endif %}" role="alert">
    {% if alert.dismissable %}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{% endif %}
    <strong>
      {% if alert.severity == 'info' %}
        <i class="fa fa-info-circle fa-fw" aria-hidden="true"></i>
      {% elif alert.severity == 'success' %}
        <i class="fa fa-check-circle fa-fw" aria-hidden="true"></i>
      {% elif alert.severity == 'warning' %}
        <i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i>
      {% elif alert.severity == 'danger' %}
        <i class="fa fa-times-circle fa-fw" aria-hidden="true"></i>
      {% endif %}
      {{ alert.header }}
    </strong> {{ alert.body }}
  </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

{% block wrapper %}
{% block content %}{% endblock %}
{% block modals %}
{% for modal in modals %}
{% if modal.enabled %}
<div class="modal fade" tabindex="-1" role="dialog" id="siteModal_{{ forloop.counter }}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-{{ modal.severity }}">
          {% if modal.severity == "info" %}
            <i class="fa fa-info-circle fa-fw" aria-hidden="true"></i> {{ modal.severity|title }}: 
          {% elif modal.severity == "success" %}
            <i class="fa fa-check-circle fa-fw" aria-hidden="true"></i> {{ modal.severity|title }}:
          {% elif modal.severity == "warning" %}
            <i class="fa fa-exclamation-circle fa-fw" aria-hidden="true"></i> {{ modal.severity|title }}: 
          {% elif modal.severity == "danger" %}
            <i class="fa fa-times-circle fa-fw" aria-hidden="true"></i> {{ modal.severity|title }}: 
          {% endif %}
          {{ modal.header }}
        </h4>
      </div>
      <div class="modal-body">
        {{ modal.body|safe }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endif %}
{% endfor %}
{% endblock %}

{% endblock %}

{% block inlinejs %}
<script type="text/javascript">
  $(window).load(function(){
    {% for modal in modals %}
    {% if modal.popup %}
    $("[id^=siteModal]").modal('show');
    {% endif %}
    {% endfor %}
  });
</script>
{% endblock %}