spor/blog/urls.py
from django.urls import path

from . import views
import search.views

urlpatterns = [
    path('', views.index),
    path('post/<slug>/', views.blog_post, name='post-detail'),
    path('posts/<year>/', views.year_archive, name='posts-year-archive'),
    path('posts/<year>/<month>/', views.month_archive, name='posts-month-archive'),
    path('posts/<year>/<month>/<day>/', views.day_archive, name='posts-day-archive'),
    path('category/<category>/', views.post_category, name="post-category"),
    path('tag/<tag>/', views.post_tag, name="post-tag"),
    path('search/', search.views.search),
    path('search/<slug>/', search.views.search_blog, name="search-blog"),
]

spor/investigations/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('case/<slug>/', views.investigation_case, name="case-detail"),
]

spor/spor/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
import home.views

urlpatterns = [
    path('about/', home.views.about),
    path('help/', home.views.help_page),
    path('events/', include('events.urls')),
    path('investigations/', include('investigations.urls')),
    path('research/', include('research.urls')),
    path('blog/', include('blog.urls')),
    path('services/', home.views.services),
    path('contact/', home.views.contact_page),
    path('area51/', include('area51.urls')),
    path(settings.ADMIN_URL, admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('', home.views.index),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spor/investigations/models.py
from __future__ import unicode_literals

from django.db import models
from home.models import TeamMember, Contact
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from django.utils.text import slugify
import os


class AudioEvidence(models.Model):
    label = models.CharField(max_length=50)
    file = models.FileField(upload_to="investigation/{0}/audio".format(1))
    details = models.TextField(blank=True, null=True)

    class Meta(object):
        verbose_name_plural = "Audio Evidence"

    def __unicode__(self):
        return self.label

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        if extension.lower() == '.mp3':
            return 'mpeg'
        if extension.lower() == '.ogg':
            return 'ogg'
        if extension.lower() == '.wav':
            return 'wav'
        return 'other'


class ImageEvidence(models.Model):
    label = models.CharField(max_length=50)
    file = models.ImageField(upload_to="investigation/{0}/image".format(1))
    details = models.TextField(blank=True, null=True)

    class Meta(object):
        verbose_name_plural = "Image Evidence"

    def __unicode__(self):
        return self.label


class PersonalExperience(models.Model):
    label = models.CharField(max_length=50)
    file = models.FileField(upload_to="investigation/{0}/text".format(1), blank=True)
    details = models.TextField(blank=True, null=True)

    class Meta(object):
        verbose_name_plural = "Personal Experiences"

    def __unicode__(self):
        return self.label


class VideoEvidence(models.Model):
    label = models.CharField(max_length=50)
    file = models.FileField(upload_to="investigation/{0}/video".format(1))
    details = models.TextField(blank=True, null=True)

    class Meta(object):
        verbose_name_plural = "Video Evidence"

    def __unicode__(self):
        return self.label

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        if extension.lower() == '.mp4':
            return 'mp4'
        if extension.lower() in ['.ogg', '.ogv', '.ogm']:
            return 'ogg'
        if extension.lower() == '.webm':
            return 'webm'
        return 'other'


class MiscEvidence(models.Model):
    label = models.CharField(max_length=50)
    file = models.FileField(upload_to="investigation/{0}/misc".format(1), blank=True)
    details = models.TextField(blank=True, null=True)

    class Meta(object):
        verbose_name_plural = "Misc Evidence"

    def __unicode__(self):
        return self.label


class GuestInvestigator(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    organization = models.CharField(max_length=255)

    def __unicode__(self):
        return "{fname} {lname}".format(fname=self.first_name, lname=self.last_name)


class Case(models.Model):
    CONCLUSIONS = (
        ("indeterminate", "Indeterminate"),
        ("in_progress", "In-Progress"),
        ("no_activity", "No Activity"),
        ("inconclusive", "Inconclusive"),
        ("active", "Active"),
        ("haunted", "Haunted"),
        ("under_review", "Under Review"),
    )

    CASE_STATUSES = (
        ("proposed", "Proposed"),
        ("accepted", "Accepted"),
        ("planning", "Planning"),
        ("scheduled", "Scheduled"),
        ("in_progress", "In-Progress"),
        ("analysis", "Analysis"),
        ("debrief", "Debrief"),
        ("completed", "Completed"),
        ("review", "Review"),
        ("rescheduled", "Rescheduled"),
        ("cancelled", "Cancelled"),
        ("incomplete", "Incomplete")
    )
    case_number = models.CharField(max_length=10, default="SPOR-00000")
    name = models.CharField(max_length=25)
    case_manager = models.ForeignKey(User, on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to="investigations/img", blank=True)
    thumbnail_200x100 = ImageSpecField(source='thumbnail', processors=[ResizeToFill(200, 100)], format='PNG', options={'quality': 100})
    thumbnail_500x300 = ImageSpecField(source='thumbnail', processors=[ResizeToFill(500, 300)], format='PNG', options={'quality': 100})
    thumbnail_700x300 = ImageSpecField(source='thumbnail', processors=[ResizeToFill(700, 300)], format='PNG', options={'quality': 100})
    location = models.ForeignKey(Contact, on_delete=models.PROTECT)
    date_occured = models.DateTimeField(blank=True, null=True)
    short_description = models.CharField(max_length=255)
    long_description = models.TextField()
    present_team_members = models.ManyToManyField(TeamMember, blank=True)
    present_guests = models.ManyToManyField(GuestInvestigator, blank=True)
    evidence_repository = models.URLField(blank=True, null=True)
    image_evidence = models.ManyToManyField(ImageEvidence, blank=True)
    audio_evidence = models.ManyToManyField(AudioEvidence, blank=True)
    video_evidence = models.ManyToManyField(VideoEvidence, blank=True)
    misc_evidence = models.ManyToManyField(MiscEvidence, blank=True)
    personal_experiences = models.ManyToManyField(PersonalExperience, blank=True)
    conclusion = models.CharField(max_length=25, choices=CONCLUSIONS, default="indeterminate")
    status = models.CharField(max_length=25, choices=CASE_STATUSES, default="proposed")
    related_cases = models.ManyToManyField('self', blank=True)
    public = models.BooleanField(default=False)

    slug = models.SlugField(unique=True, help_text="Only change this if you know what you are doing")

    def __unicode__(self):
        return self.case_number

    def full_address(self):
        return str(self.location)

    def save(self, *args, **kw):
        self.slug = slugify(self.case_number)
        super(Case, self).save(*args, **kw)

spor/investigations/views.py
from django.shortcuts import render, get_object_or_404
from .models import Case
from itertools import chain
from operator import attrgetter


def index(request):
    cases = Case.objects.filter(public=True)
    return render(request, 'investigations/index.html', {'cases': cases})


def investigation_case(request, slug):
    case = get_object_or_404(Case, slug=slug)
    related_cases = case.related_cases.filter(public=True)
    team_members = case.present_team_members.all()
    guests = case.present_guests.all()

    parties_present = sorted(chain(team_members, guests), key=attrgetter('last_name'))

    return render(request, 'investigations/case.html', {
        'case': case,
        'related_cases': related_cases,
        'parties_present': parties_present
    })

spor/investigations/templates/investigations/case.html
{% extends 'home/wrapper.html' %}

{% block content %}

<!-- Page Heading/Breadcrumbs -->
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">{{ case.name }}
			<small>{{ case.case_number }}</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="/">Home</a></li>
			<li><a href="/investigations">Investigations</a></li>
			<li class="active">{{ case.name }}</li>
		</ol>
	</div>
</div>
<!-- /.row -->

<!-- Portfolio Item Row -->
<div class="row">

	<div class="col-md-8">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				{% for i in case.image_evidence.all %}
				<li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
				{% empty %}
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				{% endfor %}
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner">
				{% for i in case.image_evidence.all %}
				<div class="item {% if forloop.first %}active{% endif %}">
					<img class="img-responsive" src="{{ MEDIA_URL }}{{ i.file.url }}" alt="{{ i.label }}">
				</div>
				{% empty %}
				<div class="item active">
					<img class="img-responsive" src="http://placehold.it/750x500&amp;text=No Images Available" alt="">
				</div>
				{% endfor %}
			</div>

			<!-- Controls -->
			<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>

	<div class="col-md-4">
		<h3>Case Description</h3>
		<p>{{ case.long_description }}</p>
		<h3>Case Details</h3>
		<p>
			<span><strong>Case Manager:</strong> {{ case.case_manager.first_name }} {{ case.case_manager.last_name }}</span>
			<br>
			<span><strong>Location:</strong> {{ case.full_address }}</span>
			<br>
			{% if case.date_occured %}
			<span><strong>Date Occured:</strong> {{ case.date_occured }}</span>
			<br>
			{% endif %}
			<span><strong>Status:</strong> {{ case.get_status_display }}</span>
			<br>
			<span><strong>Conclusion:</strong> {{ case.get_conclusion_display }}</span>
		</p>
		{% if case.evidence_repository %}<p><a target="_blank" href="{{ case.evidence_repository }}">Evidence Repository</a></p>{% endif %}
		<h3>Parties Present</h3>
		<ul>
			{% for party in parties_present %}
			<li>{{ party.first_name }} {{ party.last_name }}</li>
			{% empty %}
			<li>There were no parties at this investigation, this is most likely in error.</li>
			{% endfor %}
		</ul>
	</div>

</div>
<!-- /.row -->

<!-- Evidence Row -->
<div class="row">

	<div class="col-lg-12">
		<h3 class="page-header">Audio Evidence</h3>
	</div>

	<div class="col-lg-12">
		{% for a in case.audio_evidence.all %}
		<h4>{{ a.label }}</h4>
		<p>{{ a.details }}</p>
		<audio controls>
		  <source src="{{ MEDIA_URL }}{{ a.file.url }}" type="audio/{{ a.extension }}">
			Your browser does not support the audio element.
		</audio>
		{% empty %}
		<p>No audio evidence was collected for this investigation.</p>
		{% endfor %}
	</div>

	<div class="col-lg-12">
		<h3 class="page-header">Image Evidence</h3>
	</div>

	<div class="col-lg-12">
		{% for i in case.image_evidence.all %}
		<h4>{{ i.label }}</h4>
		<p>{{ i.details }}</p>
		<img class="img-responsive img-rounded" src="{{ MEDIA_URL }}{{ i.file.url }}" alt="{{ i.label }}">
		{% empty %}
		<p>No images were collected for this investigation.</p>
		{% endfor %}
	</div>

	<div class="col-lg-12">
		<h3 class="page-header">Video Evidence</h3>
	</div>

	<div class="col-lg-12">
		{% for v in case.video_evidence.all %}
		<h4>{{ v.label }}</h4>
		<p>{{ v.details }}</p>
		<video width="320" height="240" controls>
		  <source src="{{ MEDIA_URL }}{{ v.file.url }}" type="video/{{ v.extension }}">
			Your browser does not support the video tag.
		</video>
		{% empty %}
		<p>No video evidence was collected for this investigation.</p>
		{% endfor %}
	</div>

	<div class="col-lg-12">
		<h3 class="page-header">Personal Experiences</h3>
	</div>

	<div class="col-lg-12">
		{% for p in case.personal_experiences.all %}
		<h4>{{ p.label }}</h4>
		<p>{{ p.details }}</p>
		<p></p>
		{% empty %}
		<p>No personal experiences were collected for this investigation.</p>
		{% endfor %}
	</div>

	<div class="col-lg-12">
		<h3 class="page-header">Misc Evidence</h3>
	</div>

	<div class="col-lg-12">
		{% for m in case.misc_evidence.all %}
		<h4>{{ m.label }}</h4>
		<p>{{ m.details }}</p>
		<p></p>
		{% empty %}
		<p>No misc evidence was collected for this investigation.</p>
		{% endfor %}
	</div>

</div><!-- /.row -->

<!-- Related Projects Row -->
<div class="row">

	<div class="col-lg-12">
		<h3 class="page-header">Related Cases</h3>
	</div>

	{% for related in related_cases %}
	<div class="col-sm-3 col-xs-6">
		<a href="/investigations/case/{{ related.slug }}"><img class="img-responsive img-hover img-related img-rounded" src="{{ MEDIA_URL }}{{ related.thumbnail_500x300.url }}" alt=""></a>
	</div>
	{% empty %}
	<div class="col-md-12">
		<p>This case has no related cases.</p>
	</div>
	{% endfor %}

</div><!-- /.row -->
{% endblock %}

spor/investigations/templates/investigations/index.html
{% extends 'home/wrapper.html' %}

{% block content %}

<!-- Page Heading/Breadcrumbs -->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Investigations
      <small>Subheading</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">Investigations</li>
    </ol>
  </div>
</div>
<!-- /.row -->

{% for case in cases reversed %}
<!-- Project One -->
<div class="row">
  <div class="col-md-7">
    <a href="/investigations/case/{{ case.slug }}">
      <img class="img-responsive img-hover img-rounded" src="{{ MEDIA_URL }}{{ case.thumbnail_700x300.url }}" alt="">
    </a>
  </div>
  <div class="col-md-5">
    <h3>{{ case.name }}</h3>
    <h4>{{ case.case_number }}</h4>
    <p>{{ case.short_description }}</p>
    <a class="btn btn-primary" href="/investigations/case/{{ case.slug }}">View Case</i></a>
  </div>
</div><!-- /.row -->

<hr/>
{% if forloop.last %}
<!-- Pagination -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
  </div>
</div><!-- /.row -->
{% endif %}
{% empty %}
<h4>There are currently no public investigations at this time.</h4>
{% endfor %}

{% endblock %}